# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.1'
use_frameworks!
inhibit_all_warnings!

target 'CoreML-RDC' do

pod 'SwiftOCR'
pod 'TesseractOCRiOS'

end
